# Generated by Django 4.0.5 on 2022-08-17 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_posting_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
