# Generated by Django 4.0.5 on 2022-09-19 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_posting_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='liked',
        ),
        migrations.AddField(
            model_name='posting',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
